### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by michapixel** [999eagle/openbook-desktop#2]
I know this is no official repo and i shouldn't even be using this, but having desktop-access to openbook is kinda essential for me, especially as alpha tester.

Would it be possible to increase fontsize?

**Comment by 999eagle** [comment]
Hi, this repo isn't up to date, I only used this temporarily for releases. The main repo is on GitLab [here](https://gitlab.com/999eagle/openbook-desktop). Have you tried the latest release available there? Font scaling was already addressed there, so maybe it should work as-is :) If not, could I ask you to open an issue there? Thanks :)

**Comment by michapixel** [comment]
argh. okay, the gitlab repo is it then. works well for me, except scrolling ;) but you sure already know that.
